apiVersion: 1
groups:
    - orgId: 1
      name: Denis-setup
      folder: Denis-setup
      interval: 30s
      rules:
        - uid: f6b60487-1ade-44e6-a918-4a46b2788720
          title: Panel Title
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 21600
                to: 0
              datasourceUid: a2c71fbd-ca97-4caa-aeb3-3d53428ba620
              model:
                datasource:
                    type: prometheus
                    uid: a2c71fbd-ca97-4caa-aeb3-3d53428ba620
                disableTextWrap: false
                editorMode: builder
                expr: probe_http_status_code{instance="https://control.semiotics-lab.com"}
                fullMetaSearch: false
                includeNullMetadata: true
                instant: false
                interval: ""
                intervalMs: 15000
                legendFormat: __auto
                maxDataPoints: 43200
                range: true
                refId: A
                useBackend: false
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 200
                            - 200
                        type: outside_range
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          labels:
            namespace: telegram
          isPaused: false