apiVersion: 1
policies:
    - orgId: 1
      receiver: grafana-default-email
      group_by:
        - grafana_folder
        - alertname
      routes:
        - receiver: cp_1
          object_matchers:
            - - namespace
              - =
              - telegram
          group_wait: 30s
          group_interval: 30s
          repeat_interval: 15m
